-- Office By Overseas Skills / MySQL 8+ / import this file into the dedicated database
CREATE DATABASE IF NOT EXISTS office_overseas CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE office_overseas;
SET FOREIGN_KEY_CHECKS=0;
CREATE TABLE IF NOT EXISTS roles (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, slug VARCHAR(40) UNIQUE NOT NULL, name VARCHAR(100) NOT NULL);
CREATE TABLE IF NOT EXISTS permissions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, permission_key VARCHAR(100) UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS role_permissions (role_id BIGINT UNSIGNED NOT NULL, permission_id BIGINT UNSIGNED NOT NULL, PRIMARY KEY(role_id,permission_id), FOREIGN KEY(role_id) REFERENCES roles(id), FOREIGN KEY(permission_id) REFERENCES permissions(id));
CREATE TABLE IF NOT EXISTS locations (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, division VARCHAR(100) NOT NULL, district VARCHAR(100) NOT NULL, upazila VARCHAR(100) NOT NULL, code VARCHAR(50) UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS franchises (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, code VARCHAR(40) UNIQUE NOT NULL, name VARCHAR(180) NOT NULL, phone VARCHAR(30), email VARCHAR(190), address TEXT, location_id BIGINT UNSIGNED NULL, status ENUM('pending','active','suspended','archived') DEFAULT 'pending', direct_rate DECIMAL(6,5) NOT NULL DEFAULT 0.20000, territory_rate DECIMAL(6,5) NOT NULL DEFAULT 0.10000, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY(location_id) REFERENCES locations(id));
CREATE TABLE IF NOT EXISTS users (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, role_id BIGINT UNSIGNED NOT NULL, franchise_id BIGINT UNSIGNED NULL, name VARCHAR(160) NOT NULL, email VARCHAR(190) UNIQUE NOT NULL, phone VARCHAR(30), password_hash VARCHAR(255) NOT NULL, status ENUM('active','suspended','pending') DEFAULT 'active', last_login_at DATETIME NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY(role_id) REFERENCES roles(id), FOREIGN KEY(franchise_id) REFERENCES franchises(id), INDEX(franchise_id), INDEX(status));
CREATE TABLE IF NOT EXISTS orders (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, wordpress_order_id BIGINT UNSIGNED UNIQUE NOT NULL, franchise_id BIGINT UNSIGNED NULL, student_wp_id BIGINT UNSIGNED NOT NULL, student_name VARCHAR(160) NOT NULL, student_phone VARCHAR(30), status ENUM('pending','processing','completed','cancelled','refunded') NOT NULL DEFAULT 'pending', subtotal DECIMAL(12,2) NOT NULL, total DECIMAL(12,2) NOT NULL, attribution ENUM('direct','territory','unassigned') DEFAULT 'unassigned', payment_url TEXT, placed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, completed_at DATETIME NULL, FOREIGN KEY(franchise_id) REFERENCES franchises(id), INDEX(status), INDEX(franchise_id), INDEX(placed_at));
CREATE TABLE IF NOT EXISTS order_items (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, order_id BIGINT UNSIGNED NOT NULL, wordpress_product_id BIGINT UNSIGNED NOT NULL, name VARCHAR(255) NOT NULL, quantity INT UNSIGNED NOT NULL, unit_price DECIMAL(12,2) NOT NULL, FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS commissions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, order_id BIGINT UNSIGNED NOT NULL, franchise_id BIGINT UNSIGNED NOT NULL, rate DECIMAL(6,5) NOT NULL, amount DECIMAL(12,2) NOT NULL, status ENUM('provisional','earned','reversed') NOT NULL DEFAULT 'provisional', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, earned_at DATETIME NULL, UNIQUE KEY one_commission(order_id), FOREIGN KEY(order_id) REFERENCES orders(id), FOREIGN KEY(franchise_id) REFERENCES franchises(id));
CREATE TABLE IF NOT EXISTS wallet_ledger (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, franchise_id BIGINT UNSIGNED NOT NULL, commission_id BIGINT UNSIGNED NULL, type ENUM('credit','debit','adjustment') NOT NULL, amount DECIMAL(12,2) NOT NULL, description VARCHAR(255), created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(franchise_id) REFERENCES franchises(id), FOREIGN KEY(commission_id) REFERENCES commissions(id));
CREATE TABLE IF NOT EXISTS payouts (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, franchise_id BIGINT UNSIGNED NOT NULL, period_start DATE NOT NULL, period_end DATE NOT NULL, amount DECIMAL(12,2) NOT NULL, status ENUM('report_generated','requested','processing','paid','rejected') DEFAULT 'report_generated', payment_reference VARCHAR(190), paid_at DATETIME NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY one_period(franchise_id,period_start,period_end), FOREIGN KEY(franchise_id) REFERENCES franchises(id));
CREATE TABLE IF NOT EXISTS activity_logs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NULL, action VARCHAR(120) NOT NULL, entity_type VARCHAR(80), entity_id BIGINT UNSIGNED NULL, ip_address VARCHAR(45), metadata JSON, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX(created_at), FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS notification_logs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, channel ENUM('sms','email') NOT NULL, recipient VARCHAR(190) NOT NULL, template_key VARCHAR(100), status ENUM('queued','sent','failed') NOT NULL, provider_message_id VARCHAR(190), error_message TEXT, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX(created_at));
CREATE TABLE IF NOT EXISTS webhook_events (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, provider VARCHAR(40) NOT NULL, event_key VARCHAR(190) UNIQUE NOT NULL, payload JSON NOT NULL, processed_at DATETIME NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS settings (setting_key VARCHAR(100) PRIMARY KEY, setting_value TEXT NOT NULL, is_secret BOOLEAN DEFAULT FALSE, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
INSERT IGNORE INTO roles(slug,name) VALUES ('super_admin','Super Admin'),('admin','Admin'),('franchise_owner','Franchise Owner'),('operator','Center Operator');
INSERT IGNORE INTO permissions(permission_key) VALUES ('dashboard'),('franchises'),('students'),('orders'),('unassigned_orders'),('reports'),('logs'),('wallet'),('payouts'),('operators'),('settings');
INSERT IGNORE INTO settings(setting_key,setting_value) VALUES ('site_name','Office By Overseas Skills'),('timezone','Asia/Dhaka'),('default_direct_rate','0.20'),('default_territory_rate','0.10'),('activity_log_retention_days','30');
-- Demo administrator. Change the password after first sign-in.
-- Password: ChangeMe123! | Hash format: SHA-256(password + ':' + lowercase email)
INSERT INTO users (role_id, name, email, phone, password_hash, status)
SELECT r.id, 'Office Administrator', 'admin@overseasskills.com', '+8801700000000', SHA2('ChangeMe123!:admin@overseasskills.com', 256), 'active'
FROM roles r WHERE r.slug = 'super_admin'
  AND NOT EXISTS (SELECT 1 FROM users WHERE email = 'admin@overseasskills.com');

-- Demo location, franchise, and orders for a clean first dashboard view.
INSERT IGNORE INTO locations (division, district, upazila, code) VALUES ('Dhaka', 'Dhaka', 'Mirpur', 'DHK-MIRPUR');
INSERT IGNORE INTO franchises (code, name, phone, email, address, location_id, status)
SELECT 'FC-DHK-01', 'Dhaka North Skills Hub', '+8801711000000', 'dhaka@overseasskills.com', 'Mirpur, Dhaka', id, 'active'
FROM locations WHERE code = 'DHK-MIRPUR';
INSERT IGNORE INTO orders (wordpress_order_id, franchise_id, student_wp_id, student_name, student_phone, status, subtotal, total, attribution, placed_at)
SELECT 1001, f.id, 501, 'Nusrat Jahan', '+8801811000000', 'completed', 12500.00, 12500.00, 'direct', CURRENT_TIMESTAMP
FROM franchises f WHERE f.code = 'FC-DHK-01';

SET FOREIGN_KEY_CHECKS=1;
