'use client'

import { useEffect, useState } from 'react'
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { Bell, Building2, ChevronDown, ClipboardList, FileText, LayoutDashboard, Menu, Search, Settings, Users, WalletCards, X } from 'lucide-react'

type DashboardData = { sales:number; completedOrders:number; activeCenters:number; pendingPayouts:number; trend:{month:string;sales:number}[]; centers:{code:string;name:string;location:string|null;sales:number;orders:number;status:string}[]; orders:{id:string;student:string;center:string;amount:number;status:string}[]; configured:boolean }
const emptyData: DashboardData = { sales:0, completedOrders:0, activeCenters:0, pendingPayouts:0, trend:[], centers:[], orders:[], configured:false }
const links = [[LayoutDashboard,'Dashboard','/dashboard'],[Building2,'Franchises','/systems/franchises'],[Users,'Students','/systems/students'],[ClipboardList,'Orders','/systems/orders'],[WalletCards,'Payouts','/systems/payouts'],[FileText,'Reports','/systems/reports'],[Settings,'Settings','/systems/settings']] as const
const money = (value:number) => `৳ ${value.toLocaleString('en-BD')}`

function Stat({ icon:Icon, label, value }: { icon: typeof Users; label:string; value:string }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex size-10 items-center justify-center rounded-xl bg-blue-50 text-[#173b67]"><Icon /></div><p className="mt-5 text-sm text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold tracking-tight text-slate-900">{value}</p></div> }
function Empty({ label }: { label:string }) { return <div className="flex min-h-32 items-center justify-center rounded-xl border border-dashed border-slate-200 text-sm text-slate-400">{label}: Data Not Found</div> }

export default function DashboardPage() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [data, setData] = useState(emptyData)
  const [loading, setLoading] = useState(true)
  useEffect(() => { fetch('/api/dashboard').then(response => response.ok ? response.json() : Promise.reject()).then(payload => setData(payload.data ?? emptyData)).catch(() => setData(emptyData)).finally(() => setLoading(false)) }, [])
  return <div className="min-h-screen bg-[#f6f8fb] text-slate-900">
    <aside className="fixed inset-y-0 left-0 z-30 hidden w-64 border-r border-slate-200 bg-white lg:flex lg:flex-col"><Brand /><Navigation /><Help /></aside>
    {menuOpen && <button aria-label="Close navigation" className="fixed inset-0 z-20 bg-slate-900/30 lg:hidden" onClick={() => setMenuOpen(false)} />}
    <aside className={`fixed inset-y-0 left-0 z-30 flex w-72 flex-col border-r border-slate-200 bg-white shadow-xl transition-transform lg:hidden ${menuOpen ? 'translate-x-0' : '-translate-x-full'}`}><div className="flex items-center justify-between"><Brand /><button aria-label="Close menu" className="mr-4 rounded-lg p-2 text-slate-500 hover:bg-slate-100" onClick={() => setMenuOpen(false)}><X /></button></div><Navigation onNavigate={() => setMenuOpen(false)} /></aside>
    <main className="lg:pl-64"><header className="sticky top-0 z-10 flex min-h-20 items-center justify-between border-b border-slate-200 bg-white/95 px-4 backdrop-blur sm:px-8"><div className="flex items-center gap-3"><button aria-label="Open navigation" className="rounded-lg p-2 text-slate-600 hover:bg-slate-100 lg:hidden" onClick={() => setMenuOpen(true)}><Menu /></button><div><p className="text-xs text-slate-400">Monday, 23 September 2026</p><h1 className="text-lg font-bold text-slate-900 sm:text-xl">Good morning, Admin</h1></div></div><div className="flex items-center gap-2 sm:gap-4"><button aria-label="Search" className="hidden rounded-xl border border-slate-200 p-2.5 text-slate-500 sm:block"><Search /></button><button aria-label="Notifications" className="rounded-xl border border-slate-200 p-2.5 text-slate-500"><Bell /></button><div className="hidden items-center gap-2 sm:flex"><div className="flex size-9 items-center justify-center rounded-full bg-[#173b67] text-sm font-bold text-white">A</div><div><p className="text-sm font-semibold">Admin</p><p className="text-xs text-slate-400">Super Admin</p></div><ChevronDown className="text-slate-400" /></div></div></header>
      <div className="p-4 sm:p-8"><div className="mb-6"><p className="text-sm text-slate-500">Head office overview</p><h2 className="text-2xl font-bold">Dashboard</h2></div>
        {data.configured === false && !loading && <div className="mb-6 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800">Database data is not available. Connect MySQL and import the SQL file to populate this dashboard.</div>}
        <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={WalletCards} label="Sales" value={loading ? 'Loading…' : money(data.sales)} /><Stat icon={ClipboardList} label="Completed orders" value={loading ? 'Loading…' : data.completedOrders.toLocaleString()} /><Stat icon={Building2} label="Active centers" value={loading ? 'Loading…' : data.activeCenters.toLocaleString()} /><Stat icon={WalletCards} label="Pending payouts" value={loading ? 'Loading…' : money(data.pendingPayouts)} /></section>
        <section className="mt-6 grid gap-6 xl:grid-cols-[1.4fr_1fr]"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><div><h3 className="font-semibold">Sales trend</h3><p className="text-sm text-slate-500">Revenue from database orders</p></div></div>{data.trend.length ? <ResponsiveContainer width="100%" height={250}><AreaChart data={data.trend}><defs><linearGradient id="sales" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#173b67" stopOpacity={0.25}/><stop offset="100%" stopColor="#173b67" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e2e8f0"/><XAxis dataKey="month" axisLine={false} tickLine={false}/><YAxis hide/><Tooltip formatter={(value) => money(Number(value))}/><Area type="monotone" dataKey="sales" stroke="#173b67" fill="url(#sales)" strokeWidth={3}/></AreaChart></ResponsiveContainer> : <Empty label="Sales trend" />}</div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-semibold">Monthly sales</h3><p className="mb-4 text-sm text-slate-500">Completed and processing orders</p>{data.trend.length ? <ResponsiveContainer width="100%" height={250}><BarChart data={data.trend}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e2e8f0"/><XAxis dataKey="month" axisLine={false} tickLine={false}/><YAxis hide/><Tooltip formatter={(value) => money(Number(value))}/><Bar dataKey="sales" fill="#0f9f9a" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer> : <Empty label="Monthly sales" />}</div></section>
        <section className="mt-6 grid gap-6 xl:grid-cols-[1.1fr_1fr]"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-semibold">Top franchises</h3><p className="mb-4 text-sm text-slate-500">Ranked using current database orders</p>{data.centers.length ? <div className="flex flex-col gap-3">{data.centers.map(center => <div key={center.code} className="flex items-center justify-between rounded-xl bg-slate-50 p-3"><div><p className="font-medium">{center.name}</p><p className="text-xs text-slate-500">{center.location || 'Location: Data Not Found'} · {center.orders} orders</p></div><p className="font-semibold text-[#173b67]">{money(center.sales)}</p></div>)}</div> : <Empty label="Franchises" />}</div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-semibold">Recent orders</h3><p className="mb-4 text-sm text-slate-500">Latest orders from the database</p>{data.orders.length ? <div className="flex flex-col gap-3">{data.orders.map(order => <div key={order.id} className="flex items-center justify-between gap-3 border-b border-slate-100 pb-3 last:border-0"><div><p className="font-medium">{order.student}</p><p className="text-xs text-slate-500">{order.id} · {order.center}</p></div><div className="text-right"><p className="font-semibold">{money(order.amount)}</p><p className="text-xs capitalize text-slate-500">{order.status}</p></div></div>)}</div> : <Empty label="Orders" />}</div></section>
      </div></main></div>
}
function Brand() { return <div className="flex h-20 items-center gap-3 border-b border-slate-100 px-5"><div className="flex size-10 items-center justify-center rounded-xl bg-[#173b67] text-lg font-bold text-white">OS</div><div><p className="font-bold text-[#173b67]">Office</p><p className="text-xs text-slate-400">Overseas Skills</p></div></div> }
function Navigation({ onNavigate }: { onNavigate?: () => void }) { return <nav className="flex flex-1 flex-col gap-1 p-4">{links.map(([Icon, label, href], index) => <a key={label} href={href} onClick={onNavigate} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-medium ${index === 0 ? 'bg-blue-50 text-[#173b67]' : 'text-slate-500 hover:bg-slate-50'}`}><Icon />{label}</a>)}</nav> }
function Help() { return <div className="m-4 rounded-2xl bg-[#173b67] p-4 text-white"><p className="text-sm font-semibold">Operations guide</p><p className="mt-1 text-xs text-blue-100">Review system workflows and permissions.</p></div> }
