'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { Bell, Building2, ChevronRight, ClipboardList, FileText, LayoutDashboard, Menu, Search, Settings, Users, WalletCards, X } from 'lucide-react'

type DashboardData = { sales:number; completedOrders:number; activeCenters:number; pendingPayouts:number; trend:{month:string;sales:number}[]; centers:{id?:number;code:string;name:string;location:string|null;sales:number;orders:number;status:string}[]; orders:{id:string;student:string;center:string;amount:number;status:string}[]; configured:boolean }
const emptyData: DashboardData = { sales:0, completedOrders:0, activeCenters:0, pendingPayouts:0, trend:[], centers:[], orders:[], configured:false }
const links = [[LayoutDashboard,'Dashboard','/dashboard'],[Building2,'Centers','/systems/franchises'],[Users,'Students','/systems/students'],[ClipboardList,'Orders','/systems/orders'],[WalletCards,'Payouts','/systems/payouts'],[FileText,'Reports','/systems/reports'],[Settings,'Settings','/systems/settings']] as const
const money = (value:number) => `৳ ${value.toLocaleString('en-BD')}`

function Stat({ icon:Icon, label, value, accent }: { icon: typeof Users; label:string; value:string; accent:string }) { return <div className="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-[0_8px_30px_rgb(15,35,60,0.04)]"><div className={`flex size-10 items-center justify-center rounded-xl ${accent}`}><Icon /></div><p className="mt-5 text-sm text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold tracking-tight text-slate-950">{value}</p></div> }
function Empty({ label }: { label:string }) { return <div className="flex min-h-32 items-center justify-center rounded-xl border border-dashed border-slate-200 text-sm text-slate-400">{label}: Data Not Found</div> }

export default function DashboardPage() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [data, setData] = useState(emptyData)
  const [loading, setLoading] = useState(true)
  useEffect(() => { fetch('/api/dashboard').then(response => response.ok ? response.json() : Promise.reject()).then(payload => setData(payload.data ?? emptyData)).catch(() => setData(emptyData)).finally(() => setLoading(false)) }, [])
  return <div className="min-h-screen bg-[#f4f7fb] text-slate-900">
    <aside className="fixed inset-y-0 left-0 z-30 hidden w-64 border-r border-slate-200/80 bg-white lg:flex lg:flex-col"><Brand /><Navigation /><Help /></aside>
    {menuOpen && <button aria-label="Close navigation" className="fixed inset-0 z-20 bg-slate-950/35 backdrop-blur-sm lg:hidden" onClick={() => setMenuOpen(false)} />}
    <aside className={`fixed inset-y-0 left-0 z-30 flex w-[min(88vw,320px)] flex-col border-r border-slate-200 bg-white shadow-2xl transition-transform duration-200 lg:hidden ${menuOpen ? 'translate-x-0' : '-translate-x-full'}`}><div className="flex items-center justify-between"><Brand /><button aria-label="Close menu" className="mr-4 rounded-xl p-2.5 text-slate-500 hover:bg-slate-100" onClick={() => setMenuOpen(false)}><X /></button></div><Navigation onNavigate={() => setMenuOpen(false)} /><Help /></aside>
    <main className="lg:pl-64"><header className="sticky top-0 z-10 flex min-h-20 items-center justify-between border-b border-slate-200/80 bg-white/90 px-4 backdrop-blur-xl sm:px-8"><div className="flex items-center gap-3"><button aria-label="Open navigation" className="rounded-xl border border-slate-200 bg-white p-2.5 text-slate-600 shadow-sm hover:bg-slate-50 lg:hidden" onClick={() => setMenuOpen(true)}><Menu /></button><div><p className="text-xs font-medium uppercase tracking-[0.16em] text-slate-400">Head office</p><h1 className="text-lg font-bold text-slate-950 sm:text-xl">Good morning, Admin</h1></div></div><div className="flex items-center gap-2 sm:gap-4"><button aria-label="Search" className="hidden rounded-xl border border-slate-200 p-2.5 text-slate-500 hover:bg-slate-50 sm:block"><Search /></button><button aria-label="Notifications" className="rounded-xl border border-slate-200 p-2.5 text-slate-500 hover:bg-slate-50"><Bell /></button><div className="hidden items-center gap-2 sm:flex"><div className="flex size-9 items-center justify-center rounded-full bg-[#12375f] text-sm font-bold text-white">A</div><div><p className="text-sm font-semibold">Admin</p><p className="text-xs text-slate-400">Super Admin</p></div></div></div></header>
      <div className="p-4 sm:p-8"><div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm text-slate-500">Monday, 23 September 2026</p><h2 className="mt-1 text-3xl font-bold tracking-tight text-slate-950">Operations overview</h2><p className="mt-2 max-w-xl text-sm text-slate-500">Manage centers, orders, payouts and the people who keep Overseas Skills moving.</p></div><Link href="/systems/franchises" className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#12375f] px-4 py-2.5 text-sm font-semibold text-white shadow-lg shadow-[#12375f]/15 hover:bg-[#0e2c4d]">Manage centers <ChevronRight /></Link></div>
        {data.configured === false && !loading && <div className="mb-6 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800">No live database rows are available yet. Import the SQL seed and check your MySQL environment variables.</div>}
        <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={WalletCards} label="Sales this period" value={loading ? 'Loading…' : money(data.sales)} accent="bg-teal-50 text-teal-700" /><Stat icon={ClipboardList} label="Completed orders" value={loading ? 'Loading…' : data.completedOrders.toLocaleString()} accent="bg-blue-50 text-blue-700" /><Stat icon={Building2} label="Active centers" value={loading ? 'Loading…' : data.activeCenters.toLocaleString()} accent="bg-indigo-50 text-indigo-700" /><Stat icon={WalletCards} label="Pending payouts" value={loading ? 'Loading…' : money(data.pendingPayouts)} accent="bg-amber-50 text-amber-700" /></section>
        <section className="mt-6 grid gap-6 xl:grid-cols-[1.45fr_1fr]"><div className="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-[0_8px_30px_rgb(15,35,60,0.04)]"><div className="mb-4"><h3 className="font-semibold text-slate-950">Sales performance</h3><p className="text-sm text-slate-500">Completed order revenue from the database</p></div>{data.trend.length ? <ResponsiveContainer width="100%" height={250}><AreaChart data={data.trend}><defs><linearGradient id="sales" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#0f9f9a" stopOpacity={0.3}/><stop offset="100%" stopColor="#0f9f9a" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e2e8f0"/><XAxis dataKey="month" axisLine={false} tickLine={false}/><YAxis hide/><Tooltip formatter={(value) => money(Number(value))}/><Area type="monotone" dataKey="sales" stroke="#0f9f9a" fill="url(#sales)" strokeWidth={3}/></AreaChart></ResponsiveContainer> : <Empty label="Sales performance" />}</div><div className="rounded-2xl border border-slate-200/80 bg-[#12375f] p-5 text-white shadow-[0_8px_30px_rgb(15,35,60,0.12)]"><p className="text-sm text-blue-100">Control center</p><h3 className="mt-2 text-2xl font-bold">Everything in one place.</h3><p className="mt-3 text-sm leading-6 text-blue-100">Open a center profile to review its team, territory, order history, commission rates and current status.</p><Link href="/systems/franchises" className="mt-6 inline-flex items-center gap-2 rounded-xl bg-white px-4 py-2.5 text-sm font-semibold text-[#12375f]">Open center directory <ChevronRight /></Link><div className="mt-8 grid grid-cols-2 gap-3"><div className="rounded-xl bg-white/10 p-3"><p className="text-2xl font-bold">{data.centers.length}</p><p className="text-xs text-blue-100">Visible centers</p></div><div className="rounded-xl bg-white/10 p-3"><p className="text-2xl font-bold">{data.orders.length}</p><p className="text-xs text-blue-100">Recent orders</p></div></div></div></section>
        <section className="mt-6 grid gap-6 xl:grid-cols-[1.1fr_1fr]"><div className="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-[0_8px_30px_rgb(15,35,60,0.04)]"><div className="mb-4 flex items-center justify-between"><div><h3 className="font-semibold text-slate-950">Center performance</h3><p className="text-sm text-slate-500">Select a center for full management controls</p></div><Link href="/systems/franchises" className="text-sm font-semibold text-[#12375f]">View all</Link></div>{data.centers.length ? <div className="flex flex-col gap-3">{data.centers.map(center => <Link href={`/systems/franchises/${center.id ?? center.code}`} key={center.code} className="flex items-center justify-between rounded-xl border border-slate-100 p-3 transition hover:border-teal-200 hover:bg-teal-50/40"><div><p className="font-medium">{center.name}</p><p className="text-xs text-slate-500">{center.code} · {center.location || 'Location: Data Not Found'} · {center.orders} orders</p></div><div className="text-right"><p className="font-semibold text-[#12375f]">{money(center.sales)}</p><p className="text-xs capitalize text-slate-500">{center.status}</p></div></Link>)}</div> : <Empty label="Centers" />}</div><div className="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-[0_8px_30px_rgb(15,35,60,0.04)]"><h3 className="font-semibold text-slate-950">Recent orders</h3><p className="mb-4 text-sm text-slate-500">Latest order activity from the database</p>{data.orders.length ? <div className="flex flex-col gap-3">{data.orders.map(order => <div key={order.id} className="flex items-center justify-between gap-3 border-b border-slate-100 pb-3 last:border-0"><div><p className="font-medium">{order.student}</p><p className="text-xs text-slate-500">{order.id} · {order.center}</p></div><div className="text-right"><p className="font-semibold">{money(order.amount)}</p><p className="text-xs capitalize text-slate-500">{order.status}</p></div></div>)}</div> : <Empty label="Orders" />}</div></section>
      </div></main></div>
}
function Brand() { return <div className="flex h-20 items-center gap-3 border-b border-slate-100 px-5"><div className="flex size-10 items-center justify-center rounded-xl bg-[#12375f] text-lg font-bold text-white">OS</div><div><p className="font-bold text-[#12375f]">Office</p><p className="text-xs text-slate-400">Overseas Skills</p></div></div> }
function Navigation({ onNavigate }: { onNavigate?: () => void }) { return <nav className="flex flex-1 flex-col gap-1 p-4">{links.map(([Icon, label, href]) => <Link key={label} href={href} onClick={onNavigate} className="flex items-center justify-between rounded-xl px-3 py-3 text-sm font-medium text-slate-500 transition hover:bg-slate-50 hover:text-[#12375f]"><span className="flex items-center gap-3"><Icon />{label}</span><ChevronRight /></Link>)}</nav> }
function Help() { return <div className="m-4 rounded-2xl bg-[#12375f] p-4 text-white"><p className="text-sm font-semibold">Operations guide</p><p className="mt-1 text-xs leading-5 text-blue-100">Every page is connected to your database. Empty sections show Data Not Found instead of demo content.</p></div> }
